name: budget_tracker
description: A simple budget tracker app
publish_to: 'none' # this prevents accidental publishing

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  provider: ^6.0.0
  shared_preferences: ^2.0.15
  charts_flutter: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  generate: true
  uses-material-design: true